# Generated by Django 6.1.1 on 2026-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('tracking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('truck_stop_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.FloatField()),
            ],
        ),
    ]
