# Generated by Django 6.1.1 on 2026-09-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelPrices',
            new_name='FuelStation',
        ),
    ]
