# Generated by Django 6.1.1 on 2026-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_rename_fuelprices_fuelstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='tracking_id',
            field=models.IntegerField(),
        ),
    ]
