# Generated by Django 6.1.1 on 2026-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_fuelstation_id_alter_fuelstation_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
