# Generated by Django 6.1.1 on 2026-09-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_alter_fuelstation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
