# Generated by Django 6.1.1 on 2026-09-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_fuelstation_lat_fuelstation_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='truck_stop_name',
            field=models.CharField(max_length=50),
        ),
    ]
